### ISSUE TITLE
DEMO都跑不动，怎么给你Star？

### ISSUE THREAD

**Issue by AflyingApple** [SherlockQi/WeChatFloat#3]
Illegal redeclaration of property in class extension 'HKFloatManager' (attribute must be 'readwrite', while its primary must be 'readonly')
错误❌

**Comment by SherlockQi** [comment]
抱歉 是我疏忽了 可以了

**Comment by AflyingApple** [comment]
给你一颗小星星，以后继续努力

**Comment by SherlockQi** [comment]
哈哈哈 随手一颗星 幸福有开心
