### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by liuzhao** [SherlockQi/WeChatFloat#8]
完全用不了，怎么给star？

**Comment by SherlockQi** [comment]
> 完全用不了，怎么给star？

主要是实现思路,下了demo,看看代码,自己实现,很简单.

**Comment by liuzhao** [comment]
但是不是简单不简单的问题，主要是你自己的demo都不能运行。。。我们也想给star啊，但是是不是得先让demo能运行啊？

**Comment by SherlockQi** [comment]
报错信息方便给我看看？

发自我的 iPhone
